version: "3.9"

services:
  backend:
    build: ./backend
    container_name: qwen_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    tty: true
    stdin_open: true
